// Auto-generated. Do not edit!

// (in-package pokemon_exploration.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class StartFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_distance = null;
      this.current_error = null;
    }
    else {
      if (initObj.hasOwnProperty('current_distance')) {
        this.current_distance = initObj.current_distance
      }
      else {
        this.current_distance = 0.0;
      }
      if (initObj.hasOwnProperty('current_error')) {
        this.current_error = initObj.current_error
      }
      else {
        this.current_error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StartFeedback
    // Serialize message field [current_distance]
    bufferOffset = _serializer.float64(obj.current_distance, buffer, bufferOffset);
    // Serialize message field [current_error]
    bufferOffset = _serializer.float64(obj.current_error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StartFeedback
    let len;
    let data = new StartFeedback(null);
    // Deserialize message field [current_distance]
    data.current_distance = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [current_error]
    data.current_error = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pokemon_exploration/StartFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2a6c461fcb85ef1623333aa310560289';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float64 current_distance
    float64 current_error
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StartFeedback(null);
    if (msg.current_distance !== undefined) {
      resolved.current_distance = msg.current_distance;
    }
    else {
      resolved.current_distance = 0.0
    }

    if (msg.current_error !== undefined) {
      resolved.current_error = msg.current_error;
    }
    else {
      resolved.current_error = 0.0
    }

    return resolved;
    }
};

module.exports = StartFeedback;
