// Generated by gencpp from file pokemon_exploration/StartAction.msg
// DO NOT EDIT!


#ifndef POKEMON_EXPLORATION_MESSAGE_STARTACTION_H
#define POKEMON_EXPLORATION_MESSAGE_STARTACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pokemon_exploration/StartActionGoal.h>
#include <pokemon_exploration/StartActionResult.h>
#include <pokemon_exploration/StartActionFeedback.h>

namespace pokemon_exploration
{
template <class ContainerAllocator>
struct StartAction_
{
  typedef StartAction_<ContainerAllocator> Type;

  StartAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  StartAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::pokemon_exploration::StartActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::pokemon_exploration::StartActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::pokemon_exploration::StartActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::pokemon_exploration::StartAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pokemon_exploration::StartAction_<ContainerAllocator> const> ConstPtr;

}; // struct StartAction_

typedef ::pokemon_exploration::StartAction_<std::allocator<void> > StartAction;

typedef boost::shared_ptr< ::pokemon_exploration::StartAction > StartActionPtr;
typedef boost::shared_ptr< ::pokemon_exploration::StartAction const> StartActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pokemon_exploration::StartAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pokemon_exploration::StartAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pokemon_exploration::StartAction_<ContainerAllocator1> & lhs, const ::pokemon_exploration::StartAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pokemon_exploration::StartAction_<ContainerAllocator1> & lhs, const ::pokemon_exploration::StartAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pokemon_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pokemon_exploration::StartAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pokemon_exploration::StartAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pokemon_exploration::StartAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pokemon_exploration::StartAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pokemon_exploration::StartAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pokemon_exploration::StartAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pokemon_exploration::StartAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46eba2595d5c0596493643269ad4d382";
  }

  static const char* value(const ::pokemon_exploration::StartAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46eba2595d5c0596ULL;
  static const uint64_t static_value2 = 0x493643269ad4d382ULL;
};

template<class ContainerAllocator>
struct DataType< ::pokemon_exploration::StartAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pokemon_exploration/StartAction";
  }

  static const char* value(const ::pokemon_exploration::StartAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pokemon_exploration::StartAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"StartActionGoal action_goal\n"
"StartActionResult action_result\n"
"StartActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: pokemon_exploration/StartActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"StartGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pokemon_exploration/StartGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"float64 distance_to_wall\n"
"\n"
"================================================================================\n"
"MSG: pokemon_exploration/StartActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"StartResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pokemon_exploration/StartResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"float64 average_error\n"
"\n"
"================================================================================\n"
"MSG: pokemon_exploration/StartActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"StartFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: pokemon_exploration/StartFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 current_distance\n"
"float64 current_error\n"
;
  }

  static const char* value(const ::pokemon_exploration::StartAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pokemon_exploration::StartAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pokemon_exploration::StartAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pokemon_exploration::StartAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::pokemon_exploration::StartActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::pokemon_exploration::StartActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POKEMON_EXPLORATION_MESSAGE_STARTACTION_H
