// Generated by gencpp from file pokemon_exploration/StartActionGoal.msg
// DO NOT EDIT!


#ifndef POKEMON_EXPLORATION_MESSAGE_STARTACTIONGOAL_H
#define POKEMON_EXPLORATION_MESSAGE_STARTACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <pokemon_exploration/StartGoal.h>

namespace pokemon_exploration
{
template <class ContainerAllocator>
struct StartActionGoal_
{
  typedef StartActionGoal_<ContainerAllocator> Type;

  StartActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  StartActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::pokemon_exploration::StartGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct StartActionGoal_

typedef ::pokemon_exploration::StartActionGoal_<std::allocator<void> > StartActionGoal;

typedef boost::shared_ptr< ::pokemon_exploration::StartActionGoal > StartActionGoalPtr;
typedef boost::shared_ptr< ::pokemon_exploration::StartActionGoal const> StartActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pokemon_exploration::StartActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pokemon_exploration::StartActionGoal_<ContainerAllocator1> & lhs, const ::pokemon_exploration::StartActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pokemon_exploration::StartActionGoal_<ContainerAllocator1> & lhs, const ::pokemon_exploration::StartActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pokemon_exploration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a12a3298bb716234ccac5a75f8c2ebec";
  }

  static const char* value(const ::pokemon_exploration::StartActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa12a3298bb716234ULL;
  static const uint64_t static_value2 = 0xccac5a75f8c2ebecULL;
};

template<class ContainerAllocator>
struct DataType< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pokemon_exploration/StartActionGoal";
  }

  static const char* value(const ::pokemon_exploration::StartActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"StartGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pokemon_exploration/StartGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"float64 distance_to_wall\n"
;
  }

  static const char* value(const ::pokemon_exploration::StartActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pokemon_exploration::StartActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pokemon_exploration::StartActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::pokemon_exploration::StartGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POKEMON_EXPLORATION_MESSAGE_STARTACTIONGOAL_H
