; Auto-generated. Do not edit!


(cl:in-package pokemon_exploration-msg)


;//! \htmlinclude StartResult.msg.html

(cl:defclass <StartResult> (roslisp-msg-protocol:ros-message)
  ((average_error
    :reader average_error
    :initarg :average_error
    :type cl:float
    :initform 0.0))
)

(cl:defclass StartResult (<StartResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pokemon_exploration-msg:<StartResult> is deprecated: use pokemon_exploration-msg:StartResult instead.")))

(cl:ensure-generic-function 'average_error-val :lambda-list '(m))
(cl:defmethod average_error-val ((m <StartResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pokemon_exploration-msg:average_error-val is deprecated.  Use pokemon_exploration-msg:average_error instead.")
  (average_error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartResult>) ostream)
  "Serializes a message object of type '<StartResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'average_error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartResult>) istream)
  "Deserializes a message object of type '<StartResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'average_error) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartResult>)))
  "Returns string type for a message object of type '<StartResult>"
  "pokemon_exploration/StartResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartResult)))
  "Returns string type for a message object of type 'StartResult"
  "pokemon_exploration/StartResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartResult>)))
  "Returns md5sum for a message object of type '<StartResult>"
  "c8e56c1b61e53d0747557b0166b12a98")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartResult)))
  "Returns md5sum for a message object of type 'StartResult"
  "c8e56c1b61e53d0747557b0166b12a98")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartResult>)))
  "Returns full string definition for message of type '<StartResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float64 average_error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartResult)))
  "Returns full string definition for message of type 'StartResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float64 average_error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StartResult
    (cl:cons ':average_error (average_error msg))
))
