; Auto-generated. Do not edit!


(cl:in-package pokemon_exploration-msg)


;//! \htmlinclude StartGoal.msg.html

(cl:defclass <StartGoal> (roslisp-msg-protocol:ros-message)
  ((distance_to_wall
    :reader distance_to_wall
    :initarg :distance_to_wall
    :type cl:float
    :initform 0.0))
)

(cl:defclass StartGoal (<StartGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pokemon_exploration-msg:<StartGoal> is deprecated: use pokemon_exploration-msg:StartGoal instead.")))

(cl:ensure-generic-function 'distance_to_wall-val :lambda-list '(m))
(cl:defmethod distance_to_wall-val ((m <StartGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pokemon_exploration-msg:distance_to_wall-val is deprecated.  Use pokemon_exploration-msg:distance_to_wall instead.")
  (distance_to_wall m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartGoal>) ostream)
  "Serializes a message object of type '<StartGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'distance_to_wall))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartGoal>) istream)
  "Deserializes a message object of type '<StartGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance_to_wall) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartGoal>)))
  "Returns string type for a message object of type '<StartGoal>"
  "pokemon_exploration/StartGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartGoal)))
  "Returns string type for a message object of type 'StartGoal"
  "pokemon_exploration/StartGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartGoal>)))
  "Returns md5sum for a message object of type '<StartGoal>"
  "d51d1fafc04bc3bcfc4202d9e0715200")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartGoal)))
  "Returns md5sum for a message object of type 'StartGoal"
  "d51d1fafc04bc3bcfc4202d9e0715200")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartGoal>)))
  "Returns full string definition for message of type '<StartGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float64 distance_to_wall~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartGoal)))
  "Returns full string definition for message of type 'StartGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%float64 distance_to_wall~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StartGoal
    (cl:cons ':distance_to_wall (distance_to_wall msg))
))
