// Auto-generated. Do not edit!

// (in-package turtlebot3_wall_follower.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class StartResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.average_error = null;
    }
    else {
      if (initObj.hasOwnProperty('average_error')) {
        this.average_error = initObj.average_error
      }
      else {
        this.average_error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StartResult
    // Serialize message field [average_error]
    bufferOffset = _serializer.float64(obj.average_error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StartResult
    let len;
    let data = new StartResult(null);
    // Deserialize message field [average_error]
    data.average_error = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'turtlebot3_wall_follower/StartResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c8e56c1b61e53d0747557b0166b12a98';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    float64 average_error
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StartResult(null);
    if (msg.average_error !== undefined) {
      resolved.average_error = msg.average_error;
    }
    else {
      resolved.average_error = 0.0
    }

    return resolved;
    }
};

module.exports = StartResult;
