(cl:defpackage turtlebot3_wall_follower-msg
  (:use )
  (:export
   "<STARTACTION>"
   "STARTACTION"
   "<STARTACTIONFEEDBACK>"
   "STARTACTIONFEEDBACK"
   "<STARTACTIONGOAL>"
   "STARTACTIONGOAL"
   "<STARTACTIONRESULT>"
   "STARTACTIONRESULT"
   "<STARTFEEDBACK>"
   "STARTFEEDBACK"
   "<STARTGOAL>"
   "STARTGOAL"
   "<STARTRESULT>"
   "STARTRESULT"
  ))

