// Generated by gencpp from file turtlebot3_wall_follower/StartGoal.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_WALL_FOLLOWER_MESSAGE_STARTGOAL_H
#define TURTLEBOT3_WALL_FOLLOWER_MESSAGE_STARTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_wall_follower
{
template <class ContainerAllocator>
struct StartGoal_
{
  typedef StartGoal_<ContainerAllocator> Type;

  StartGoal_()
    : distance_to_wall(0.0)  {
    }
  StartGoal_(const ContainerAllocator& _alloc)
    : distance_to_wall(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_to_wall_type;
  _distance_to_wall_type distance_to_wall;





  typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> const> ConstPtr;

}; // struct StartGoal_

typedef ::turtlebot3_wall_follower::StartGoal_<std::allocator<void> > StartGoal;

typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartGoal > StartGoalPtr;
typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartGoal const> StartGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator1> & lhs, const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator2> & rhs)
{
  return lhs.distance_to_wall == rhs.distance_to_wall;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator1> & lhs, const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_wall_follower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d51d1fafc04bc3bcfc4202d9e0715200";
  }

  static const char* value(const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd51d1fafc04bc3bcULL;
  static const uint64_t static_value2 = 0xfc4202d9e0715200ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_wall_follower/StartGoal";
  }

  static const char* value(const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"float64 distance_to_wall\n"
;
  }

  static const char* value(const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_to_wall);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_wall_follower::StartGoal_<ContainerAllocator>& v)
  {
    s << indent << "distance_to_wall: ";
    Printer<double>::stream(s, indent + "  ", v.distance_to_wall);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_WALL_FOLLOWER_MESSAGE_STARTGOAL_H
