// Generated by gencpp from file turtlebot3_wall_follower/StartFeedback.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_WALL_FOLLOWER_MESSAGE_STARTFEEDBACK_H
#define TURTLEBOT3_WALL_FOLLOWER_MESSAGE_STARTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_wall_follower
{
template <class ContainerAllocator>
struct StartFeedback_
{
  typedef StartFeedback_<ContainerAllocator> Type;

  StartFeedback_()
    : current_distance(0.0)
    , current_error(0.0)  {
    }
  StartFeedback_(const ContainerAllocator& _alloc)
    : current_distance(0.0)
    , current_error(0.0)  {
  (void)_alloc;
    }



   typedef double _current_distance_type;
  _current_distance_type current_distance;

   typedef double _current_error_type;
  _current_error_type current_error;





  typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct StartFeedback_

typedef ::turtlebot3_wall_follower::StartFeedback_<std::allocator<void> > StartFeedback;

typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartFeedback > StartFeedbackPtr;
typedef boost::shared_ptr< ::turtlebot3_wall_follower::StartFeedback const> StartFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator1> & lhs, const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_distance == rhs.current_distance &&
    lhs.current_error == rhs.current_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator1> & lhs, const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_wall_follower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a6c461fcb85ef1623333aa310560289";
  }

  static const char* value(const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a6c461fcb85ef16ULL;
  static const uint64_t static_value2 = 0x23333aa310560289ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_wall_follower/StartFeedback";
  }

  static const char* value(const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 current_distance\n"
"float64 current_error\n"
;
  }

  static const char* value(const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_distance);
      stream.next(m.current_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_wall_follower::StartFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_distance: ";
    Printer<double>::stream(s, indent + "  ", v.current_distance);
    s << indent << "current_error: ";
    Printer<double>::stream(s, indent + "  ", v.current_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_WALL_FOLLOWER_MESSAGE_STARTFEEDBACK_H
